### ISSUE TITLE
_persist_pixels: TOCTOU on inst.pixel_array between the None-check and tobytes()

### ISSUE THREAD

**Issue by kvnlng** [kvnlng/Isocenter#288]
Surfaced by the review of #280 (the #274/#250 work); pre-existing, not introduced by #280.

## The race

`SqliteStore._persist_pixels` checks `inst.pixel_array is None` **outside** the `_pixel_swap_lock` (the early-return that takes the loader arm), then re-reads `inst.pixel_array.tobytes()` **inside** the lock. Nothing holds `inst.pixel_array` stable across that gap.

`entities.Instance.unload_pixel_data()` sets `self.pixel_array = None` with **no lock at all**. So a background save can pass the `is None` check (array present), and a concurrent `unload_pixel_data()` — from `release_memory()`, or the redaction path's own `finally` — can null it before `tobytes()` runs, raising `AttributeError: 'NoneType' object has no attribute 'tobytes'` inside the save. The save then fails / retries.

This is **degradation, not corruption**: no attested-PHI outcome, just a save that raises where it should no-op. It is a likely cousin of the intermittent 3.14t `Incomplete read from sidecar. Expected N, got 0` seen during #274 reproduction — another face of two unsynchronized readers/writers on the same lazy pixel state under true parallelism.

## Fix directions

- Snapshot `arr = inst.pixel_array` once inside the lock and branch on the local (both the None-check and the `tobytes()` read the same reference); and/or
- Bring `unload_pixel_data()`'s `pixel_array = None` (and the symmetric materialize in `get_pixel_data`) under the same `_pixel_swap_lock`, so "is there a resident array" and "publish/clear it" are one atomic question per instance.

The #274 fix deliberately scoped itself to the attested-PHI corruption and left this degradation path open; it wants its own change so the invariant ("one writer traverses read→publish per instance") is extended to the unload/materialize side rather than only the two persist writers.

Refs #280, #274. No milestone.
